//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTable
    {
        public string DocumentName { get; set; }
        public string Title { get; set; }
        public string CollectionType { get; set; }
        public string Language { get; set; }
        public string CollectionID { get; set; }
        public string CMG { get; set; }
        public string DisclosureLevel { get; set; }
        public string DocumentType { get; set; }
        public string DocumentTypeDetail { get; set; }
        public string Regions { get; set; }
        public string TopicCategories { get; set; }
        public string PublicationCode { get; set; }
        public string ContentTopic { get; set; }
        public string SearchKeywords { get; set; }
        public string EmbeddedLinks { get; set; }
        public string PublicationDestinations { get; set; }
        public string ProductLines { get; set; }
        public string OriginalFilename { get; set; }
        public string BusinessDefinedProperties { get; set; }
        public string Authors { get; set; }
        public string ContentVersion { get; set; }
        public string VersionLabel { get; set; }
        public string ProjectName { get; set; }
        public string CollectionMasterID { get; set; }
        public string CreationDate { get; set; }
        public string ContentUpdateDate { get; set; }
    }
}
