//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocMatrix
    {
        public string MatrixID { get; set; }
        public string DateFinal { get; set; }
        public string DocDiscipline { get; set; }
        public string DocumentType { get; set; }
        public string DocumentName { get; set; }
        public string ProductNumber { get; set; }
        public string DocPartNumber { get; set; }
        public string DocServiceLevel { get; set; }
        public string ServiceKitPart { get; set; }
        public string ConcentraPDFID { get; set; }
        public string Languages { get; set; }
        public string SupplyChainStrategy { get; set; }
        public string QRCodeURL { get; set; }
        public string LinkDocConcentraID { get; set; }
        public string VideoURL { get; set; }
        public string Comments { get; set; }
        public string BrightcoveLink { get; set; }
        public string BDP { get; set; }
        public string ProductName { get; set; }
    }
}
