//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicList
    {
        public string ID { get; set; }
        public string ProductSelection { get; set; }
        public string Web { get; set; }
        public string Intellifix { get; set; }
        public string IssueSignature { get; set; }
        public string UG { get; set; }
        public string WLG { get; set; }
        public string SRM { get; set; }
        public string OnsiteInstallGuide { get; set; }
        public string STR { get; set; }
        public string WBT1_3 { get; set; }
        public string WBT4_6 { get; set; }
        public string Title { get; set; }
        public string ConcentraID { get; set; }
        public string Link { get; set; }
        public string BrightcoveLink { get; set; }
        public string ProductSource { get; set; }
        public string DocumentSource { get; set; }
        public string Core { get; set; }
        public string DesignTeamNotes { get; set; }
        public string ProjectManagerNotes { get; set; }
        public string SMEPartnerNotes { get; set; }
        public string ProLeEnterprise { get; set; }
        public string Asset { get; set; }
        public string DisclosureLevel { get; set; }
        public string Status { get; set; }
        public string OwnerPM { get; set; }
        public string EmbeddedLinks { get; set; }
        public string BDP { get; set; }
        public string AquentGrouping { get; set; }
        public string Onboarded { get; set; }
        public string ProductTitle { get; set; }
    }
}
